import { renderProjects } from "../../components/project-renderer.js";
import { createEditorState } from "./state.js";
import { createMediaPreviewStore } from "./media-previews.js";
import { splitPlainTextParagraphs } from "../../project-core/plain-text-paragraphs.js";

const clone = (value) => structuredClone(value);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);

export const descriptionToEditorText = (items) => Array.isArray(items) ? items.join("\n\n") : "";
export const editorTextToDescription = (value) => splitPlainTextParagraphs(String(value ?? ""));

/**
 * Auth- and transport-free CMS Lite UI. Persistence and account controls are injected so a
 * public sandbox cannot acquire an API, session, or credential dependency by accident.
 */
export function mountCmsEditor({ root, initialState, storage, chrome = {}, mediaResolver = { resolve: (src) => src }, onPersistedChange = () => {} }) {
  const previewStore = createMediaPreviewStore();
  const editor = createEditorState({ initialState, storage });
  let snapshot; let errorMessage = ""; let previewLocale = "ru"; let connectionStatus = "CONNECTED";
  const selected = () => snapshot.workingState.projects.find((project) => project.id === snapshot.selectedProjectId) ?? null;
  const title = (project) => project?.title.ru || project?.title.en || project?.id || "Новый проект";
  const field = (label, path, value, type = "input") => `<label class="cms-field"><span>${label}</span>${type === "textarea" ? `<textarea data-field="${path}">${escapeHtml(value)}</textarea>` : `<input data-field="${path}" value="${escapeHtml(value)}">`}</label>`;
  const mutate = (fn) => { snapshot = editor.update((state) => { const project = state.projects.find((item) => item.id === snapshot.selectedProjectId); if (project) fn(project); }); };
  const setPath = (target, path, value) => { const parts = path.split("."); let cursor = target; parts.slice(0, -1).forEach((part) => { cursor = cursor[part]; }); cursor[parts.at(-1)] = value; };
  const pending = (id) => snapshot.pendingMedia.get(id) ?? null;
  const mediaById = (project, id) => ["desktop", "mobile"].flatMap((kind) => project.gallery[kind]).find((media) => media.id === id);
  const mediaKind = (project, id) => ["desktop", "mobile"].find((kind) => project.gallery[kind].some((media) => media.id === id)) ?? pending(id)?.galleryKind;
  const galleryItems = (project, kind) => [...project.gallery[kind].map((media) => ({ ...media, transient: pending(media.id) })), ...[...snapshot.pendingMedia.values()].filter((media) => media.projectId === project.id && media.galleryKind === kind && !media.replacesCanonical)];
  const projectId = () => `new-project-${crypto.randomUUID().slice(0, 8)}`;

  const list = (caption, property, project) => {
    const count = Math.max(project[property].ru.length, project[property].en.length);
    return `<fieldset class="cms-fieldset"><legend>${caption}</legend>${Array.from({ length: count }, (_, index) => `<div class="cms-list-row">${field("RU", `${property}.ru.${index}`, project[property].ru[index] ?? "", "textarea")}${field("EN", `${property}.en.${index}`, project[property].en[index] ?? "", "textarea")}<button class="cms-row-delete" data-remove-list="${property}:${index}" type="button">Удалить</button></div>`).join("")}<button class="cms-add" data-add-list="${property}" type="button">+ Добавить пункт</button></fieldset>`;
  };
  const links = (project) => `<fieldset class="cms-fieldset"><legend>Ссылки</legend>${project.links.map((link, index) => `<div class="cms-link-row">${field("RU", `link.${index}.label.ru`, link.label.ru)}${field("EN", `link.${index}.label.en`, link.label.en)}${field("URL", `link.${index}.url`, link.url)}<label class="cms-field"><span>Target</span><select data-link-target="${index}"><option value="_blank" ${link.target === "_blank" ? "selected" : ""}>_blank</option><option value="_self" ${link.target === "_self" ? "selected" : ""}>_self</option></select></label><button class="cms-row-delete" data-remove-link="${index}" type="button">Удалить</button></div>`).join("")}<button class="cms-add" data-add-link type="button">+ Добавить ссылку</button></fieldset>`;
  const mediaPreview = (url) => url ? `<img src="${escapeHtml(url)}" alt="">` : '<p class="cms-media-card__missing">Изображение недоступно</p>';
  const gallery = (caption, kind, project) => `<fieldset class="cms-fieldset"><legend>${caption}</legend><label class="cms-field"><span>Добавить изображение</span><input data-add-media="${kind}" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="cms-gallery">${galleryItems(project, kind).map((media) => { const url = media.objectUrl ?? media.transient?.objectUrl ?? previewStore.get(media.id)?.objectUrl ?? mediaResolver.resolve(media.src); return `<article class="cms-media-card ${kind === "mobile" ? "cms-media-card--mobile" : ""}">${mediaPreview(url)}<p>${escapeHtml(media.id)}</p><label class="cms-field"><span>Replace</span><input data-replace-media="${media.id}" type="file" accept="image/jpeg,image/png,image/webp"></label>${field("Alt RU", `media.${media.id}.alt.ru`, media.alt.ru)}${field("Alt EN", `media.${media.id}.alt.en`, media.alt.en)}<label class="cms-field"><span>Presentation</span><select data-media-presentation="${media.id}"><option value="cover" ${media.presentation === "cover" ? "selected" : ""}>cover</option><option value="contain" ${media.presentation === "contain" ? "selected" : ""}>contain</option></select></label><button class="cms-row-delete" data-delete-media="${media.id}" type="button">Удалить</button></article>`; }).join("")}</div></fieldset>`;
  const form = (project) => !project ? `<section class="cms-editor"><p>Проект не выбран.</p></section>` : `<section class="cms-editor"><div class="cms-editor-heading"><h1>${escapeHtml(title(project))}</h1><label class="cms-status-control"><span>Статус</span><select data-status><option value="draft" ${project.status === "draft" ? "selected" : ""}>draft</option><option value="published" ${project.status === "published" ? "selected" : ""}>published</option></select></label></div>${project.status === "draft" ? '<span class="cms-draft-preview">Предпросмотр черновика</span>' : ""}${errorMessage ? `<p class="cms-form-error" role="alert">${escapeHtml(errorMessage)}</p>` : ""}<fieldset class="cms-fieldset"><legend>Основное</legend><div class="cms-field-grid"><label class="cms-field"><span>Stable ID</span><input value="${project.id}" disabled></label><label class="cms-field"><span>Порядок</span><input data-order type="number" min="0" value="${project.order}"></label>${field("Категория RU", "category.ru", project.category.ru)}${field("Категория EN", "category.en", project.category.en)}${field("Название RU", "title.ru", project.title.ru)}${field("Название EN", "title.en", project.title.en)}${field("Роль RU", "role.ru", project.role.ru)}${field("Роль EN", "role.en", project.role.en)}${field("Status label RU", "statusLabel.ru", project.statusLabel.ru)}${field("Status label EN", "statusLabel.en", project.statusLabel.en)}</div></fieldset><fieldset class="cms-fieldset"><legend>Описание</legend><div class="cms-field-grid">${field("RU", "description.ru", descriptionToEditorText(project.description.ru), "textarea")}${field("EN", "description.en", descriptionToEditorText(project.description.en), "textarea")}</div></fieldset>${list("Функции", "features", project)}${list("Примечания", "notes", project)}<fieldset class="cms-fieldset"><legend>Технологии</legend><div class="cms-chips">${project.techStack.map((tag, index) => `<span class="cms-chip">${escapeHtml(tag)}<button data-remove-tag="${index}" type="button">×</button></span>`).join("")}</div><form data-tag-form><label class="cms-field"><span>Новая технология</span><input name="tag"></label><button class="cms-add" type="submit">Добавить</button></form></fieldset>${links(project)}${gallery("Desktop Gallery", "desktop", project)}${gallery("Mobile Gallery", "mobile", project)}</section>`;
  const preview = (project) => { const result = clone(project); result.status = "published"; ["desktop", "mobile"].forEach((kind) => { result.gallery[kind] = result.gallery[kind].flatMap((media) => { const local = pending(media.id); const src = local?.objectUrl ?? mediaResolver.resolve(media.src); return src ? [{ ...media, src }] : []; }); result.gallery[kind].push(...[...snapshot.pendingMedia.values()].filter((media) => media.projectId === project.id && media.galleryKind === kind && !media.replacesCanonical).map((media) => ({ id: media.id, src: media.objectUrl, alt: media.alt, ariaLabel: media.ariaLabel, presentation: media.presentation }))); }); return result; };
  const render = () => { const project = selected(); root.innerHTML = `<header class="cms-topbar"><span class="cms-topbar__title">${escapeHtml(chrome.title ?? "Portfolio CMS")}</span>${chrome.notice ? `<span class="cms-demo-notice">${escapeHtml(chrome.notice)}</span>` : ""}<span data-connection-status class="cms-connection" role="status"></span><span data-save-state class="cms-save-state ${snapshot.dirty ? "is-dirty" : ""}"></span><button data-save-all class="button button--primary" type="button">Save All</button>${chrome.actionsHtml?.() ?? ""}</header><div class="cms-layout"><aside class="cms-sidebar"><strong>Проекты</strong><div class="cms-project-list">${snapshot.workingState.projects.map((item) => `<div class="cms-project-row"><button class="cms-project-row__select ${item.id === snapshot.selectedProjectId ? "is-selected" : ""}" data-select="${item.id}" type="button">${escapeHtml(title(item))}<span class="cms-status">${item.status === "published" ? "Опубликован" : "Черновик"}</span></button><button class="cms-delete" data-delete="${item.id}" type="button">×</button></div>`).join("")}</div><button class="cms-add" data-new-project type="button">+ Новый проект</button></aside>${form(project)}<aside class="cms-preview"><h2>Предпросмотр</h2><div><button data-preview-locale="ru" type="button">RU</button><button data-preview-locale="en" type="button">EN</button></div><div data-preview-root></div></aside></div>${chrome.extraHtml?.() ?? ""}`; refreshLiveUi(); };
  const updateChrome = () => { const saved = root.querySelector("[data-save-state]"); if (saved) { saved.classList.toggle("is-dirty", snapshot.dirty); saved.textContent = snapshot.dirty ? "Есть несохраненные правки" : "Все изменения сохранены"; } const connection = root.querySelector("[data-connection-status]"); if (connection) connection.textContent = connectionStatus === "BUSY" ? "Сохранение" : connectionStatus === "DISCONNECTED" ? "Хранилище недоступно" : (chrome.connectionLabel ?? "Подключено: память"); };
  const renderPreview = () => { const project = selected(); const previewRoot = root.querySelector("[data-preview-root]"); if (previewRoot && project) renderProjects({ root: previewRoot, projects: [preview(project)], locale: previewLocale }); };
  const refreshLiveUi = () => { updateChrome(); renderPreview(); };
  const refresh = () => render();
  root.addEventListener("input", (event) => { const target = event.target; if (target.matches("[data-field]")) mutate((project) => { const [scope, ...path] = target.dataset.field.split("."); if (scope === "link") setPath(project.links[Number(path.shift())], path.join("."), target.value); else if (scope === "media") { const id = path.shift(); const item = pending(id); if (item) snapshot = editor.updatePendingMedia(id, (media) => setPath(media, path.join("."), target.value)); else setPath(mediaById(project, id), path.join("."), target.value); } else if (scope === "description") project.description[path[0]] = editorTextToDescription(target.value); else setPath(project, target.dataset.field, target.value); }); else if (target.matches("[data-order]")) mutate((project) => { project.order = Number(target.value); }); else return; refreshLiveUi(); });
  root.addEventListener("change", async (event) => { const target = event.target; if (target.matches("[data-status]")) mutate((project) => { project.status = target.value; }); else if (target.matches("[data-link-target]")) mutate((project) => { project.links[Number(target.dataset.linkTarget)].target = target.value; }); else if (target.matches("[data-media-presentation]")) { const item = pending(target.dataset.mediaPresentation); if (item) snapshot = editor.updatePendingMedia(target.dataset.mediaPresentation, (media) => { media.presentation = target.value; }); else mutate((project) => { mediaById(project, target.dataset.mediaPresentation).presentation = target.value; }); } else if (target.matches("[data-replace-media], [data-add-media]")) { const file = target.files?.[0]; if (!file) return; try { await storage.validateMedia?.(file); } catch (error) { errorMessage = error.message; refresh(); return; } const project = selected(); let id = target.dataset.replaceMedia; const adding = !id; const kind = target.dataset.addMedia ?? mediaKind(project, id); const existing = mediaById(project, id) ?? pending(id); if (!id) id = `${kind}-${crypto.randomUUID().slice(0, 8)}`; snapshot = editor.setPendingMedia({ id, projectId: project.id, galleryKind: kind, file, objectUrl: previewStore.replace(id, file), replacesCanonical: Boolean(existing && mediaById(project, id)), alt: existing?.alt ?? project.title, ariaLabel: existing?.ariaLabel ?? project.title, presentation: existing?.presentation ?? (kind === "mobile" ? "contain" : "cover") }); } else return; refresh(); });
  root.addEventListener("click", async (event) => { const target = event.target.closest("button"); if (!target) return; if (target.dataset.select) snapshot = editor.select(target.dataset.select); else if (target.dataset.newProject !== undefined) snapshot = editor.createProject(projectId()); else if (target.dataset.delete) snapshot = editor.deleteProject(target.dataset.delete); else if (target.dataset.addList) mutate((project) => { project[target.dataset.addList].ru.push(""); project[target.dataset.addList].en.push(""); }); else if (target.dataset.removeList) { const [property, index] = target.dataset.removeList.split(":"); mutate((project) => { project[property].ru.splice(Number(index), 1); project[property].en.splice(Number(index), 1); }); } else if (target.dataset.removeTag) mutate((project) => project.techStack.splice(Number(target.dataset.removeTag), 1)); else if (target.dataset.addLink !== undefined) mutate((project) => project.links.push({ label: { ru: "", en: "" }, url: "", target: "_blank" })); else if (target.dataset.removeLink) mutate((project) => project.links.splice(Number(target.dataset.removeLink), 1)); else if (target.dataset.deleteMedia) { previewStore.remove(target.dataset.deleteMedia); snapshot = editor.clearPendingMedia(target.dataset.deleteMedia); mutate((project) => ["desktop", "mobile"].forEach((kind) => { project.gallery[kind] = project.gallery[kind].filter((media) => media.id !== target.dataset.deleteMedia); })); } else if (target.dataset.previewLocale) { previewLocale = target.dataset.previewLocale; } else if (target.dataset.saveAll !== undefined) { connectionStatus = "BUSY"; updateChrome(); try { const result = await editor.save(); snapshot = result.snapshot; errorMessage = result.saved ? "" : result.validation.issues.map((issue) => `${issue.path}: ${issue.message}`).slice(0, 4).join("; "); connectionStatus = "CONNECTED"; if (result.saved) onPersistedChange(snapshot.serverState); } catch (error) { errorMessage = error?.message || "Хранилище временно недоступно."; connectionStatus = "DISCONNECTED"; } } else if (await chrome.onAction?.(target.dataset, { snapshot, editor, previewStore, refresh })) { return; } else return; refresh(); });
  root.addEventListener("submit", (event) => { if (!event.target.matches("[data-tag-form]")) return; event.preventDefault(); const value = String(new FormData(event.target).get("tag") ?? "").trim(); if (value) mutate((project) => { if (!project.techStack.includes(value)) project.techStack.push(value); }); refresh(); });
  const dispose = () => previewStore.dispose();
  return { load: async () => { snapshot = await editor.load(); render(); return snapshot; }, dispose, snapshot: () => snapshot, refresh, editor };
}
