FROM nginxinc/nginx-unprivileged:1.29-bookworm

USER root

ARG PUBLIC_API_BASE_URL
ARG PUBLIC_CMS_LOGIN_URL
RUN test -n "$PUBLIC_API_BASE_URL" && test -n "$PUBLIC_CMS_LOGIN_URL" && \
  printf 'globalThis.__PORTFOLIO_CONFIG__ = Object.freeze({ apiBaseUrl: "%s", cmsLoginUrl: "%s" });\n' "$PUBLIC_API_BASE_URL" "$PUBLIC_CMS_LOGIN_URL" > /tmp/runtime-config.js

COPY index.html script.js i18n.js style.css runtime-config.js /usr/share/nginx/html/
COPY components config data mappers services images /usr/share/nginx/html/
COPY deploy/nginx/public.conf /etc/nginx/conf.d/default.conf
RUN cp /tmp/runtime-config.js /usr/share/nginx/html/runtime-config.js

EXPOSE 8080
USER 101
