import { boolean, date, index, integer, jsonb, pgTable, primaryKey, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { adminUsers } from "./admin-auth.js";
import { mediaAssets } from "./media-assets.js";
import { mediaOrientationEnum, mediaPresentationEnum, projectGalleryKindEnum } from "./project-media.js";
import { projectRevisions } from "./project-revisions.js";
import { projects } from "./projects.js";

const locale = text("locale").$type<"ru" | "en">();

export const projectLocalePublicationRevisions = pgTable("project_locale_publication_revisions", {
  id: uuid("id").primaryKey(), projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), locale,
  sourceEditorRevisionId: uuid("source_editor_revision_id").notNull().references(() => projectRevisions.id, { onDelete: "restrict" }), snapshot: jsonb("snapshot").notNull(),
  createdBy: uuid("created_by").references(() => adminUsers.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull(),
}, (table) => [unique("project_locale_publication_revisions_id_project_locale_uq").on(table.id, table.projectId, table.locale), unique("project_locale_publication_revisions_source_locale_uq").on(table.projectId, table.locale, table.sourceEditorRevisionId), index("project_locale_publication_revisions_project_locale_created_idx").on(table.projectId, table.locale, table.createdAt)]);

export const projectLocalePublications = pgTable("project_locale_publications", {
  projectId: uuid("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }), locale,
  currentPublicationRevisionId: uuid("current_publication_revision_id").references(() => projectLocalePublicationRevisions.id, { onDelete: "restrict" }), publishedAt: timestamp("published_at", { withTimezone: true }), publicationGeneration: integer("publication_generation").notNull().default(0), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(),
}, (table) => [primaryKey({ columns: [table.projectId, table.locale], name: "project_locale_publications_pk" }), index("project_locale_publications_current_pointer_idx").on(table.currentPublicationRevisionId)]);

export const projectLocalePublicationProjects = pgTable("project_locale_publication_projects", {
  publicationRevisionId: uuid("publication_revision_id").primaryKey().references(() => projectLocalePublicationRevisions.id, { onDelete: "cascade" }), projectId: uuid("project_id").notNull(), locale,
  slug: text("slug").notNull(), galleryId: text("gallery_id").notNull(), sortOrder: integer("sort_order").notNull(), projectType: text("project_type"), startedAt: date("started_at"), endedAt: date("ended_at"), isOngoing: boolean("is_ongoing").notNull(), title: text("title").notNull(), subtitle: text("subtitle"), description: text("description").notNull(), role: text("role").notNull(), statusLabel: text("status_label").notNull(), displayType: text("display_type").notNull(), technologiesTitle: text("technologies_title"),
}, (table) => [index("project_locale_publication_projects_locale_sort_idx").on(table.locale, table.sortOrder)]);

function orderedTextTable(name: "project_locale_publication_features" | "project_locale_publication_notes") { return pgTable(name, { publicationRevisionId: uuid("publication_revision_id").notNull().references(() => projectLocalePublicationProjects.publicationRevisionId, { onDelete: "cascade" }), stableId: uuid("stable_id").notNull(), sortOrder: integer("sort_order").notNull(), text: text("text").notNull() }, (table) => [primaryKey({ columns: [table.publicationRevisionId, table.stableId] }), uniqueIndex(`${name}_order_uq`).on(table.publicationRevisionId, table.sortOrder)]); }
export const projectLocalePublicationFeatures = orderedTextTable("project_locale_publication_features");
export const projectLocalePublicationNotes = orderedTextTable("project_locale_publication_notes");
export const projectLocalePublicationTechnologies = pgTable("project_locale_publication_technologies", { publicationRevisionId: uuid("publication_revision_id").notNull().references(() => projectLocalePublicationProjects.publicationRevisionId, { onDelete: "cascade" }), technologySlug: text("technology_slug").notNull(), technologyName: text("technology_name").notNull(), sortOrder: integer("sort_order").notNull() }, (table) => [primaryKey({ columns: [table.publicationRevisionId, table.technologySlug] }), uniqueIndex("project_locale_publication_technologies_order_uq").on(table.publicationRevisionId, table.sortOrder)]);
export const projectLocalePublicationLinks = pgTable("project_locale_publication_links", { publicationRevisionId: uuid("publication_revision_id").notNull().references(() => projectLocalePublicationProjects.publicationRevisionId, { onDelete: "cascade" }), stableId: uuid("stable_id").notNull(), sortOrder: integer("sort_order").notNull(), url: text("url").notNull(), label: text("label").notNull() }, (table) => [primaryKey({ columns: [table.publicationRevisionId, table.stableId] }), uniqueIndex("project_locale_publication_links_order_uq").on(table.publicationRevisionId, table.sortOrder)]);
export const projectLocalePublicationMedia = pgTable("project_locale_publication_media", { publicationRevisionId: uuid("publication_revision_id").notNull().references(() => projectLocalePublicationProjects.publicationRevisionId, { onDelete: "cascade" }), stableId: text("stable_id").notNull(), mediaAssetId: uuid("media_asset_id").notNull().references(() => mediaAssets.id, { onDelete: "restrict" }), sourceType: text("source_type").$type<"legacy" | "managed">().notNull(), externalKey: text("external_key").notNull(), path: text("path"), role: text("role").notNull(), orientation: mediaOrientationEnum("orientation").notNull(), galleryKind: projectGalleryKindEnum("gallery_kind").notNull(), presentation: mediaPresentationEnum("presentation").notNull(), sortOrder: integer("sort_order").notNull(), width: integer("width"), height: integer("height"), altText: text("alt_text").notNull(), ariaLabel: text("aria_label").notNull() }, (table) => [primaryKey({ columns: [table.publicationRevisionId, table.stableId] }), uniqueIndex("project_locale_publication_media_order_uq").on(table.publicationRevisionId, table.galleryKind, table.sortOrder)]);
