import { randomUUID } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import pg from "pg";
import { createDatabase } from "../../src/db/client.js";
import { loadFrontendProjects, seedProjects } from "../../scripts/seed-projects.js";

export type TemporaryDatabaseCleanupResult = { poolClosed: boolean; connectionsTerminated: number; databaseDropped: boolean; databaseAbsentAfterDrop: boolean };
export type TemporarySchema16Database = { databaseName: string; databaseUrl: string; pool: pg.Pool; migrationTrackingCount: number; cleanup(): Promise<TemporaryDatabaseCleanupResult> };
const safe = (name: string) => /^[a-z][a-z0-9_]{0,62}_test$/.test(name) && name !== "portfolio_test";
const quote = (name: string) => `"${name.replaceAll('"', '""')}"`;
export const temporarySchema16Name = (prefix = "portfolio_schema16") => `${prefix}_${randomUUID().replaceAll("-", "").slice(0, 20)}_test`;
export function validateTemporarySchema16Environment(env: NodeJS.ProcessEnv, destination: string) { if (env.DATABASE_PURPOSE !== "test") throw Object.assign(new Error("Temporary DB requires DATABASE_PURPOSE=test."), { code: "TEMP_DB_PURPOSE_INVALID" }); if (!env.DATABASE_URL) throw Object.assign(new Error("Temporary DB requires DATABASE_URL."), { code: "TEMP_DB_URL_MISSING" }); let url: URL; try { url = new URL(env.DATABASE_URL); } catch { throw Object.assign(new Error("Temporary DB URL is invalid."), { code: "TEMP_DB_URL_INVALID" }); } const source = decodeURIComponent(url.pathname.slice(1)); const approved = env.TEST_DATABASE_NAME ?? "portfolio_test"; if (!source || source !== approved || !source.endsWith("_test")) throw Object.assign(new Error("Temporary DB source is not the runner test contour."), { code: "TEMP_DB_SOURCE_INVALID" }); if (!safe(destination)) throw Object.assign(new Error("Temporary DB destination name is invalid."), { code: "TEMP_DB_DESTINATION_INVALID" }); if (destination === source) throw Object.assign(new Error("Temporary DB destination must differ from source."), { code: "TEMP_DB_DESTINATION_EQUALS_SOURCE" }); return { url, source }; }
export async function createTemporarySchema16Database(options: { namePrefix?: string; env?: NodeJS.ProcessEnv; failAfterCreate?: boolean; failAfterPool?: boolean; seedLegacy?: boolean; beforeFullMigration?: (pool: pg.Pool) => Promise<void> } = {}): Promise<TemporarySchema16Database> { const env = options.env ?? process.env; const name = temporarySchema16Name(options.namePrefix); const { url: sourceUrl } = validateTemporarySchema16Environment(env, name); const destinationUrl = new URL(sourceUrl); destinationUrl.pathname = `/${encodeURIComponent(name)}`; const admin = new pg.Pool({ connectionString: sourceUrl.toString() }); let pool: pg.Pool | undefined; let folder = ""; let cleanupResult: TemporaryDatabaseCleanupResult | undefined;
  const cleanup = async (): Promise<TemporaryDatabaseCleanupResult> => { if (cleanupResult) return cleanupResult; let terminated = 0; if (pool) { await pool.end(); pool = undefined; } const sessions = await admin.query<{ pid: number }>("select pid from pg_stat_activity where datname=$1 and pid<>pg_backend_pid()", [name]); terminated = sessions.rowCount ?? 0; if (terminated) await admin.query("select pg_terminate_backend(pid) from pg_stat_activity where datname=$1 and pid<>pg_backend_pid()", [name]); await admin.query(`drop database if exists ${quote(name)} with (force)`); const absent = !(await admin.query("select 1 from pg_database where datname=$1", [name])).rowCount; await admin.end(); if (folder) await rm(folder, { recursive: true, force: true }); return cleanupResult = { poolClosed: true, connectionsTerminated: terminated, databaseDropped: true, databaseAbsentAfterDrop: absent }; };
  try { await admin.query(`create database ${quote(name)}`); if (options.failAfterCreate) throw Object.assign(new Error("Injected temporary DB failure."), { code: "TEMP_DB_INJECTED_FAILURE" }); pool = new pg.Pool({ connectionString: destinationUrl.toString() }); await pool.query("drop schema public cascade"); await pool.query("create schema public"); await pool.query("drop schema if exists drizzle cascade"); if (options.failAfterPool) throw Object.assign(new Error("Injected temporary DB failure."), { code: "TEMP_DB_INJECTED_FAILURE" }); folder = await mkdtemp(join(tmpdir(), "portfolio-schema16-")); await mkdir(join(folder, "meta")); const journal = JSON.parse(await readFile(resolve("./drizzle/meta/_journal.json"), "utf8")); const tags = journal.entries.filter((entry: { tag: string }) => /^00(0[0-9]|1[0-5])_/.test(entry.tag)); for (const entry of tags) await writeFile(join(folder, `${entry.tag}.sql`), await readFile(resolve("./drizzle", `${entry.tag}.sql`), "utf8")); const bootstrap = tags.filter((entry: { tag: string }) => /^000[0-7]_/.test(entry.tag)); await writeFile(join(folder, "meta/_journal.json"), `${JSON.stringify({ version: journal.version, dialect: journal.dialect, entries: bootstrap })}\n`); await migrate(createDatabase(pool), { migrationsFolder: folder }); if (options.seedLegacy ?? true) await seedProjects(pool, await loadFrontendProjects(), { mode: "legacy-bootstrap" }); await options.beforeFullMigration?.(pool); await writeFile(join(folder, "meta/_journal.json"), `${JSON.stringify({ version: journal.version, dialect: journal.dialect, entries: tags })}\n`); await migrate(createDatabase(pool), { migrationsFolder: folder }); const count = Number((await pool.query<{ count: string }>("select count(*)::text as count from drizzle.__drizzle_migrations")).rows[0]!.count); if (count !== 16) throw new Error(`Temporary DB migration tracking is ${count}, expected 16.`); return { databaseName: name, databaseUrl: destinationUrl.toString(), pool, migrationTrackingCount: count, cleanup }; } catch (error) { await cleanup().catch(() => undefined); throw error; }
}
