CREATE TABLE "project_links" ("id" uuid PRIMARY KEY NOT NULL,"project_id" uuid NOT NULL REFERENCES "projects"("id") ON DELETE CASCADE,"url" text NOT NULL CHECK (btrim("url") <> ''),"sort_order" integer NOT NULL,"created_at" timestamptz NOT NULL DEFAULT now(),"updated_at" timestamptz NOT NULL DEFAULT now());--> statement-breakpoint
CREATE UNIQUE INDEX "project_links_project_sort_order_uq" ON "project_links" ("project_id", "sort_order");--> statement-breakpoint
CREATE TABLE "project_link_translations" ("project_link_id" uuid NOT NULL REFERENCES "project_links"("id") ON DELETE CASCADE,"locale" text NOT NULL CHECK ("locale" IN ('ru','en')),"label" text NOT NULL CHECK (btrim("label") <> ''),PRIMARY KEY ("project_link_id", "locale"));--> statement-breakpoint

DO $$
DECLARE item record; fixture_project_count integer;
BEGIN
  SELECT count(*) INTO fixture_project_count FROM "projects" WHERE "external_key" IN ('construction-management-control-center','project-bradbury','foodai');
  IF fixture_project_count NOT IN (0, 3) THEN RAISE EXCEPTION 'project link migration: partial CMCC, Project Bradbury, and FoodAI legacy baseline'; END IF;
  IF fixture_project_count = 3 AND EXISTS (SELECT 1 FROM "projects" p LEFT JOIN "project_translations" t ON t."project_id"=p."id" AND t."locale" IN ('ru','en') WHERE p."external_key" IN ('construction-management-control-center','project-bradbury','foodai') GROUP BY p."id" HAVING count(*) FILTER (WHERE t."locale"='ru') <> 1 OR count(*) FILTER (WHERE t."locale"='en') <> 1) THEN RAISE EXCEPTION 'project link migration: fixture project must have exactly one RU and one EN translation'; END IF;
  FOR item IN SELECT p."external_key",p."primary_url",p."secondary_url",max(t."primary_action_label") FILTER (WHERE t."locale"='ru') primary_ru,max(t."primary_action_label") FILTER (WHERE t."locale"='en') primary_en,max(t."secondary_action_label") FILTER (WHERE t."locale"='ru') secondary_ru,max(t."secondary_action_label") FILTER (WHERE t."locale"='en') secondary_en FROM "projects" p JOIN "project_translations" t ON t."project_id"=p."id" WHERE p."external_key" IN ('construction-management-control-center','project-bradbury','foodai') GROUP BY p."id" LOOP
    IF (nullif(btrim(coalesce(item."primary_url",'')),'') IS NULL) <> (nullif(btrim(coalesce(item.primary_ru,'')),'') IS NULL) OR (nullif(btrim(coalesce(item."primary_url",'')),'') IS NULL) <> (nullif(btrim(coalesce(item.primary_en,'')),'') IS NULL) THEN RAISE EXCEPTION 'project link migration: partial primary slot for %', item."external_key"; END IF;
    IF (nullif(btrim(coalesce(item."secondary_url",'')),'') IS NULL) <> (nullif(btrim(coalesce(item.secondary_ru,'')),'') IS NULL) OR (nullif(btrim(coalesce(item."secondary_url",'')),'') IS NULL) <> (nullif(btrim(coalesce(item.secondary_en,'')),'') IS NULL) THEN RAISE EXCEPTION 'project link migration: partial secondary slot for %', item."external_key"; END IF;
  END LOOP;
END $$;--> statement-breakpoint

WITH mapping("external_key","slot","id","sort_order") AS (VALUES
 ('construction-management-control-center','primary','91000000-0000-4000-8000-000000000001'::uuid,10),('construction-management-control-center','secondary','91000000-0000-4000-8000-000000000002'::uuid,20),('project-bradbury','primary','92000000-0000-4000-8000-000000000001'::uuid,10),('project-bradbury','secondary','92000000-0000-4000-8000-000000000002'::uuid,20),('foodai','primary','93000000-0000-4000-8000-000000000001'::uuid,10),('foodai','secondary','93000000-0000-4000-8000-000000000002'::uuid,20)
), pivot AS (SELECT p."id" project_id,p."external_key",p."primary_url",p."secondary_url",max(t."primary_action_label") FILTER (WHERE t."locale"='ru') primary_ru,max(t."primary_action_label") FILTER (WHERE t."locale"='en') primary_en,max(t."secondary_action_label") FILTER (WHERE t."locale"='ru') secondary_ru,max(t."secondary_action_label") FILTER (WHERE t."locale"='en') secondary_en FROM "projects" p JOIN "project_translations" t ON t."project_id"=p."id" GROUP BY p."id"), fixture AS (SELECT m."id",p.project_id,m."sort_order",CASE m."slot" WHEN 'primary' THEN p."primary_url" ELSE p."secondary_url" END url,CASE m."slot" WHEN 'primary' THEN p.primary_ru ELSE p.secondary_ru END ru,CASE m."slot" WHEN 'primary' THEN p.primary_en ELSE p.secondary_en END en FROM mapping m JOIN pivot p ON p."external_key"=m."external_key"), inserted AS (INSERT INTO "project_links" ("id","project_id","url","sort_order") SELECT "id",project_id,url,"sort_order" FROM fixture WHERE nullif(btrim(coalesce(url,'')),'') IS NOT NULL RETURNING "id")
INSERT INTO "project_link_translations" ("project_link_id","locale","label") SELECT f."id",v.locale,v.label FROM fixture f JOIN inserted i ON i."id"=f."id" CROSS JOIN LATERAL (VALUES ('ru',f.ru),('en',f.en)) v(locale,label);--> statement-breakpoint
DO $$ BEGIN IF EXISTS (SELECT 1 FROM "project_links" l LEFT JOIN "project_link_translations" t ON t."project_link_id"=l."id" GROUP BY l."id" HAVING count(t."locale") <> 2) THEN RAISE EXCEPTION 'project link migration: created link lacks one locale'; END IF; END $$;
