import { z } from "zod";

export type ProjectLink = { id: string; url: string; sortOrder: number; label: { ru: string; en: string } };
export const allowedProjectAnchors = new Set(["#hero", "#featured-projects", "#skills", "#services", "#about", "#contact"]);
export type LegacyLinkSlot = "primary" | "secondary";
export type LegacyLinkIdentity = { projectExternalKey: string; slot: LegacyLinkSlot; id: string; sortOrder: number };
export const legacyLinkIdentities: readonly LegacyLinkIdentity[] = [
  { projectExternalKey: "construction-management-control-center", slot: "primary", id: "91000000-0000-4000-8000-000000000001", sortOrder: 10 }, { projectExternalKey: "construction-management-control-center", slot: "secondary", id: "91000000-0000-4000-8000-000000000002", sortOrder: 20 },
  { projectExternalKey: "project-bradbury", slot: "primary", id: "92000000-0000-4000-8000-000000000001", sortOrder: 10 }, { projectExternalKey: "project-bradbury", slot: "secondary", id: "92000000-0000-4000-8000-000000000002", sortOrder: 20 },
  { projectExternalKey: "foodai", slot: "primary", id: "93000000-0000-4000-8000-000000000001", sortOrder: 10 }, { projectExternalKey: "foodai", slot: "secondary", id: "93000000-0000-4000-8000-000000000002", sortOrder: 20 },
];
const draftItem = z.object({ id: z.string().uuid(), url: z.string().max(2048), sortOrder: z.number().int(), label: z.object({ ru: z.string().max(2000), en: z.string().max(2000) }) }).strict();
export const projectLinksDraftSchema = z.array(draftItem).superRefine((links, ctx) => { for (const key of ["id", "sortOrder"] as const) { const seen = new Set<string | number>(); for (const [index, link] of links.entries()) { if (seen.has(link[key])) ctx.addIssue({ code: "custom", path: [index, key], message: `Duplicate link ${key}.` }); seen.add(link[key]); } } });
export function parseDraftProjectLinks(links: unknown): ProjectLink[] { return projectLinksDraftSchema.parse(links); }
// Keep this allowlist synchronized with CMS and public mapper; no shared runtime package spans all three builds.
export function classifyPublishableProjectLink(value: string): { kind: "anchor" | "external"; canonical: string } | null { const trimmed = value.trim(); if (allowedProjectAnchors.has(trimmed)) return { kind: "anchor", canonical: trimmed }; if (trimmed.startsWith("#")) return null; try { const url = new URL(trimmed); return url.protocol === "https:" ? { kind: "external", canonical: url.toString() } : null; } catch { return null; } }
export function assertPublishableProjectLinks(links: ProjectLink[]): void { if (!links.length) throw new Error("Missing required links publication content."); const urls = new Set<string>(); const ids = new Set<string>(); const sortOrders = new Set<number>(); for (const [index, link] of links.entries()) { if (ids.has(link.id)) throw new Error(`Duplicate links.${index}.id publication content.`); ids.add(link.id); if (sortOrders.has(link.sortOrder)) throw new Error(`Duplicate links.${index}.sortOrder publication content.`); sortOrders.add(link.sortOrder); if (!link.url.trim()) throw new Error(`Missing required links.${index}.url publication content.`); const classified = classifyPublishableProjectLink(link.url); if (!classified) throw new Error(`Invalid links.${index}.url publication content.`); if (!link.label.ru) throw new Error(`Missing required links.${index}.label.ru publication content.`); if (!link.label.en) throw new Error(`Missing required links.${index}.label.en publication content.`); const canonical = `${classified.kind}:${classified.canonical}`; if (urls.has(canonical)) throw new Error(`Duplicate links.${index}.url publication content.`); urls.add(canonical); } }
export const LEGACY_LINK_CONVERSION_ERROR = "LEGACY_LINK_CONVERSION_ERROR";
export function convertLegacyProjectLinks(input: { projectExternalKey: string; legacyLinks: { primary?: { href?: string } | null; secondary?: { href?: string } | null }; translations: { ru: { primaryActionLabel?: string | null; secondaryActionLabel?: string | null }; en: { primaryActionLabel?: string | null; secondaryActionLabel?: string | null } } }): ProjectLink[] { const result: ProjectLink[]=[]; for (const slot of ["primary","secondary"] as const) { const identity=legacyLinkIdentities.find((item)=>item.projectExternalKey===input.projectExternalKey&&item.slot===slot); const url=input.legacyLinks[slot]?.href?.trim()??""; const ru=input.translations.ru[slot==="primary"?"primaryActionLabel":"secondaryActionLabel"]?.trim()??""; const en=input.translations.en[slot==="primary"?"primaryActionLabel":"secondaryActionLabel"]?.trim()??""; if (!url&&!ru&&!en) continue; if (!identity||!url||!ru||!en) throw Object.assign(new Error(`Cannot convert ${slot} link for ${input.projectExternalKey}.`),{code:LEGACY_LINK_CONVERSION_ERROR}); result.push({id:identity.id,url,sortOrder:identity.sortOrder,label:{ru,en}}); } return result; }
