import { useEffect, useRef, useState, type ReactNode } from "react";
import { API_BASE_URL, ApiError } from "../api/client";
import { deleteDraft, deleteProject, listRevisions, publishDraft, saveDraft, uploadMedia } from "../api/projects";
import type { DraftContent, Locale, ManagedMedia, MediaOrientation, MediaPresentation, ProjectEditor, ProjectGalleryKind, ProjectRevision } from "../api/types";
import { AccessibleDialog } from "./AccessibleDialog";

type InspectorMode = "editor" | "history";
interface Props { editor: ProjectEditor | null; locale: Locale; loading: boolean; onSaved: () => Promise<ProjectEditor | null>; onProjectDeleted?: (projectId: string) => Promise<void>; onPreview: (content: DraftContent) => void; onDirtyChange: (dirty: boolean) => void; }
type RemovalTarget = { id: string; galleryKind: ProjectGalleryKind; position: number; label: string; thumbnailUrl: string | null };
type FocusTarget = { galleryKind: ProjectGalleryKind; nextId: string | null; previousId: string | null };
type LinkFieldErrors = Record<string, { url?: string; labelRu?: string; labelEn?: string; row?: string }>;
const allowedProjectAnchors = new Set(["#hero", "#featured-projects", "#skills", "#services", "#about", "#contact"]);
const linkUrlGuidance = "Укажите HTTPS-адрес или внутренний якорь: #hero, #featured-projects, #skills, #services, #about, #contact.";
const anchorGuidance = "Используйте один из разрешённых внутренних якорей: #hero, #featured-projects, #skills, #services, #about, #contact.";

const clone = <T,>(value: T): T => structuredClone(value);
const transliteration: Record<string, string> = { а: "a", б: "b", в: "v", г: "g", д: "d", е: "e", ё: "e", ж: "zh", з: "z", и: "i", й: "y", к: "k", л: "l", м: "m", н: "n", о: "o", п: "p", р: "r", с: "s", т: "t", у: "u", ф: "f", х: "h", ц: "ts", ч: "ch", ш: "sh", щ: "sch", ъ: "", ы: "y", ь: "", э: "e", ю: "yu", я: "ya" };
function automaticSlug(value: string) { return value.toLowerCase().split("").map((letter) => transliteration[letter] ?? letter).join("").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 110); }
// Keep this allowlist synchronized with the backend and public mapper; no shared runtime package spans all three builds.
function classifyPublicationLink(value: string): { kind: "anchor" | "external"; canonical: string } | null { const trimmed = value.trim(); if (allowedProjectAnchors.has(trimmed)) return { kind: "anchor", canonical: trimmed }; if (trimmed.startsWith("#")) return null; try { const parsed = new URL(trimmed); return parsed.protocol === "https:" ? { kind: "external", canonical: parsed.toString() } : null; } catch { return null; } }
function validatePublicationLinks(links: DraftContent["links"]): LinkFieldErrors {
  const errors: LinkFieldErrors = {}; const canonical = new Set<string>();
  for (const link of links) {
    const url = link.url.trim(); const ru = link.label.ru.trim(); const en = link.label.en.trim(); const current: LinkFieldErrors[string] = {};
    if (!url && !ru && !en) current.row = "Удалите пустую ссылку или заполните её полностью.";
    if (!url) current.url = linkUrlGuidance;
    if (!ru) current.labelRu = "Укажите название ссылки на русском языке.";
    if (!en) current.labelEn = "Укажите название ссылки на английском языке.";
    if (url) { const classified = classifyPublicationLink(url); if (!classified) current.url = url.startsWith("#") ? anchorGuidance : url.startsWith("http:") ? "Внешние ссылки должны начинаться с https://." : linkUrlGuidance; else { const key = `${classified.kind}:${classified.canonical}`; if (canonical.has(key)) current.url = "Эта ссылка уже добавлена."; else canonical.add(key); } }
    if (Object.keys(current).length) errors[link.id] = current;
  }
  return errors;
}
const mediaCopy = {
  en: {
    vertical: "Мобильные изображения", horizontal: "Десктопные изображения", verticalDescription: "Изображения для мобильной галереи.", horizontalDescription: "Изображения для десктопной галереи.",
    removeTitle: "Удалить изображение?", removeDescription: "Изображение будет удалено из черновика проекта. До сохранения можно отменить несохранённые изменения.", cancel: "Отмена", remove: "Удалить изображение", dimensionsUnavailable: "Размеры недоступны", imageDimensions: (width: number, height: number) => `Размеры изображения: ${width} на ${height} пикселей`, moved: (position: number, total: number, group: string) => `Изображение перемещено на позицию ${position} из ${total} в группе «${group}».`,
  },
  ru: {
    vertical: "Мобильные изображения", horizontal: "Десктопные изображения", verticalDescription: "Изображения для мобильной галереи.", horizontalDescription: "Изображения для десктопной галереи.",
    removeTitle: "Удалить изображение?", removeDescription: "Изображение будет удалено из черновика текущего проекта. До сохранения изменений можно отменить несохранённые правки.", cancel: "Отмена", remove: "Удалить изображение", dimensionsUnavailable: "Размеры недоступны", imageDimensions: (width: number, height: number) => `Размер изображения: ${width} на ${height} пикселей`, moved: (position: number, total: number, group: string) => `Изображение перемещено на позицию ${position} из ${total} в группе «${group}».`,
  },
} as const;

export function ProjectInspector({ editor, locale, loading, onSaved, onProjectDeleted, onPreview, onDirtyChange }: Props) {
  const [form, setForm] = useState<DraftContent | null>(null); const [baseline, setBaseline] = useState("");
  const [saving, setSaving] = useState(false); const [publishing, setPublishing] = useState(false); const [deletingDraft, setDeletingDraft] = useState(false); const [deletingProject, setDeletingProject] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState<string | null>(null); const [confirming, setConfirming] = useState(false); const [confirmDeleteDraft, setConfirmDeleteDraft] = useState(false); const [confirmDeleteProject, setConfirmDeleteProject] = useState(false); const [confirmReload, setConfirmReload] = useState(false); const [mismatch, setMismatch] = useState<{ file: File; galleryKind: ProjectGalleryKind; width: number; height: number } | null>(null);
  const [removal, setRemoval] = useState<RemovalTarget | null>(null); const [removing, setRemoving] = useState(false); const [reorderAnnouncement, setReorderAnnouncement] = useState({ sequence: 0, message: "" });
  const [mode, setMode] = useState<InspectorMode>("editor"); const [history, setHistory] = useState<ProjectRevision[]>([]); const [historyLoading, setHistoryLoading] = useState(false); const [historyError, setHistoryError] = useState<string | null>(null);
  const [linkErrors, setLinkErrors] = useState<LinkFieldErrors>({});
  const opener = useRef<HTMLButtonElement>(null); const removalFocus = useRef<FocusTarget | null>(null); const removalInProgress = useRef(false); const linkValidationActive = useRef(false); const onPreviewRef = useRef(onPreview);
  const dirty = form !== null && JSON.stringify(form) !== baseline;
  const linkValidationSummary = Object.keys(linkErrors).length ? "Исправьте ошибки в ссылках перед публикацией." : null;
  const copy = mediaCopy[locale];

  useEffect(() => { onPreviewRef.current = onPreview; }, [onPreview]);
  function applyEditor(nextEditor: ProjectEditor) { const content = clone(nextEditor.editable.content); setForm(content); setBaseline(JSON.stringify(content)); setError(null); linkValidationActive.current = false; setLinkErrors({}); onPreviewRef.current(content); }
  // Rehydrate only when authoring identity changes; preview updates must not discard unsaved form state.
  useEffect(() => { if (editor) applyEditor(editor); }, [editor?.project.id, editor?.editable.revisionId]);
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => { if (!dirty) return; const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ""; }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  useEffect(() => {
    const target = removalFocus.current;
    if (!target) return;
    const frame = requestAnimationFrame(() => {
      const focusElement = document.getElementById(target.nextId ? `media-remove-${target.nextId}` : "")
        ?? document.getElementById(target.previousId ? `media-remove-${target.previousId}` : "")
        ?? document.getElementById(`${target.galleryKind}-media-title`);
      focusElement?.focus();
      removalFocus.current = null;
    });
    return () => cancelAnimationFrame(frame);
  }, [form]);
  useEffect(() => {
    if (mode !== "history" || !editor) return;
    let cancelled = false;
    setHistoryLoading(true); setHistoryError(null);
    void listRevisions(editor.project.slug).then((response) => {
      if (!cancelled) setHistory(response.data);
    }).catch((value: unknown) => {
      if (!cancelled) setHistoryError(value instanceof ApiError ? value.message : "Не удалось загрузить историю изменений.");
    }).finally(() => {
      if (!cancelled) setHistoryLoading(false);
    });
    return () => { cancelled = true; };
  }, [mode, editor?.project.slug]);

  if (loading) return <section className="editor editor-state">Загрузка редактора...</section>;
  if (!editor || !form) return <section className="editor editor-state">Выберите проект для редактирования.</section>;
  const activeEditor = editor;
  const update = (mutate: (next: DraftContent) => void) => { const next = clone(form); mutate(next); setForm(next); onPreview(next); };
  function setPublicationLinkErrors(nextErrors: LinkFieldErrors) { linkValidationActive.current = Object.keys(nextErrors).length > 0; setLinkErrors(nextErrors); }
  const updateLinks = (mutate: (next: DraftContent) => void) => { const next = clone(form!); mutate(next); setForm(next); onPreview(next); if (linkValidationActive.current) setPublicationLinkErrors(validatePublicationLinks(next.links)); };
  function requestPublish() { const nextErrors = validatePublicationLinks(form!.links); if (Object.keys(nextErrors).length) { setPublicationLinkErrors(nextErrors); return; } setPublicationLinkErrors({}); setConfirming(true); }
  const text = form.translations[locale];
  const groupItems = (galleryKind: ProjectGalleryKind) => form.media.filter((asset) => asset.galleryKind === galleryKind).sort((a, b) => a.sortOrder - b.sortOrder);

  async function save() { setSaving(true); setError(null); try { const body = { publicationCapability: "legacy" as const, baseRevisionId: activeEditor.published?.revisionId ?? null, expectedDraftRevisionId: activeEditor.draft?.revisionId ?? null, content: form! }; await saveDraft(activeEditor.project.slug, body); const refreshed = await onSaved(); if (refreshed) applyEditor(refreshed); } catch (value) { const apiError = value instanceof ApiError ? value : null; setError(apiError?.code === "DRAFT_CONFLICT" ? "Проект был изменён в другой сессии. Обновите данные перед повторным сохранением." : apiError?.message ?? "Не удалось сохранить черновик."); } finally { setSaving(false); } }
  async function publish() { const nextErrors = validatePublicationLinks(form!.links); if (Object.keys(nextErrors).length) { setPublicationLinkErrors(nextErrors); setConfirming(false); return; } if (!activeEditor.draft) { setError("Сначала сохраните черновик."); return; } setPublishing(true); setError(null); try { await publishDraft(activeEditor.project.slug, activeEditor.draft.revisionId); setConfirming(false); const refreshed = await onSaved(); if (refreshed) applyEditor(refreshed); } catch (value) { const apiError = value instanceof ApiError ? value : null; setError(["DRAFT_CONFLICT", "PUBLISH_CONFLICT", "DRAFT_NOT_FOUND"].includes(apiError?.code ?? "") ? "Проект был изменён в другой сессии. Обновите данные перед повторным сохранением." : apiError?.message ?? "Не удалось опубликовать черновик."); } finally { setPublishing(false); } }
  async function removeDraft() { if (!activeEditor.draft || deletingDraft) return; setDeletingDraft(true); setError(null); try { await deleteDraft(activeEditor.project.slug, activeEditor.draft.revisionId); setConfirmDeleteDraft(false); const refreshed = await onSaved(); if (refreshed) applyEditor(refreshed); } catch (value) { const apiError = value instanceof ApiError ? value : null; setError(apiError?.code === "DRAFT_CONFLICT" ? "Проект был изменён в другой сессии. Обновите данные перед повторным сохранением." : apiError?.message ?? "Не удалось удалить черновик."); } finally { setDeletingDraft(false); } }
  async function removeProject() { if (activeEditor.published || deletingProject) return; setDeletingProject(true); setError(null); try { await deleteProject(activeEditor.project.slug); setConfirmDeleteProject(false); await onProjectDeleted?.(activeEditor.project.id); } catch (value) { const apiError = value instanceof ApiError ? value : null; setError(apiError?.code === "PUBLISHED_PROJECT_DELETE_FORBIDDEN" ? "Проект уже опубликован в другой сессии и не может быть удалён." : apiError?.message ?? "Не удалось удалить проект."); } finally { setDeletingProject(false); } }
  async function reloadLatestDraft() { const refreshed = await onSaved(); if (refreshed) applyEditor(refreshed); setConfirmReload(false); }
  async function addMedia(file: File | undefined, galleryKind: ProjectGalleryKind, confirm = false) { if (!file) return; const orientation: MediaOrientation = galleryKind === "mobile" ? "vertical" : "horizontal"; setUploading(true); setError(null); try { const uploaded = await uploadMedia(activeEditor.project.slug, file, orientation, confirm); update((next) => { const group = next.media.filter((item) => item.galleryKind === galleryKind); next.media.push({ id: crypto.randomUUID(), sourceType: "managed", assetId: uploaded.data.assetId, role: "gallery", orientation, galleryKind, presentation: galleryKind === "mobile" ? "contain" : "cover", sortOrder: group.length ? Math.max(...group.map((item) => item.sortOrder)) + 10 : 10, width: uploaded.data.width, height: uploaded.data.height, translations: { en: { alt: "", ariaLabel: "" }, ru: { alt: "", ariaLabel: "" } } }); }); setMismatch(null); } catch (value) { const apiError = value instanceof ApiError ? value : null; const details = apiError?.details as { detectedWidth?: number; detectedHeight?: number } | undefined; if (apiError?.code === "media_orientation_mismatch" && details?.detectedWidth && details.detectedHeight) setMismatch({ file, galleryKind, width: details.detectedWidth, height: details.detectedHeight }); else setError(apiError?.message ?? "Не удалось загрузить изображение."); } finally { setUploading(false); } }
  function reorder(galleryKind: ProjectGalleryKind, position: number, direction: -1 | 1) {
    const group = groupItems(galleryKind); const nextPosition = position + direction;
    if (!group[nextPosition]) return;
    update((next) => { const items = next.media.filter((item) => item.galleryKind === galleryKind).sort((a, b) => a.sortOrder - b.sortOrder); [items[position].sortOrder, items[nextPosition].sortOrder] = [items[nextPosition].sortOrder, items[position].sortOrder]; });
    const label = galleryKind === "mobile" ? copy.vertical : copy.horizontal;
    setReorderAnnouncement((current) => ({ sequence: current.sequence + 1, message: copy.moved(nextPosition + 1, group.length, label) }));
  }
  function requestRemoval(asset: DraftContent["media"][number], position: number) {
    const label = asset.translations[locale].alt || `${asset.galleryKind === "mobile" ? copy.vertical : copy.horizontal} ${position + 1}`;
    const thumbnailUrl = asset.sourceType === "managed" ? `${API_BASE_URL}/api/v1/media/${asset.assetId}/thumbnail` : null;
    setRemoval({ id: asset.id, galleryKind: asset.galleryKind, position, label, thumbnailUrl });
  }
  function confirmRemoval() {
    if (!removal || removalInProgress.current) return;
    removalInProgress.current = true; setRemoving(true);
    try {
      const group = groupItems(removal.galleryKind); const currentPosition = group.findIndex((item) => item.id === removal.id);
      removalFocus.current = { galleryKind: removal.galleryKind, nextId: group[currentPosition + 1]?.id ?? null, previousId: group[currentPosition - 1]?.id ?? null };
      update((next) => {
        next.media.splice(next.media.findIndex((item) => item.id === removal.id), 1);
        next.media.filter((item) => item.galleryKind === removal.galleryKind).sort((a, b) => a.sortOrder - b.sortOrder).forEach((item, index) => { item.sortOrder = (index + 1) * 10; });
      });
      setRemoval(null);
    } finally { removalInProgress.current = false; setRemoving(false); }
  }

  return <section className="editor" aria-labelledby="editor-title">
    <div className="editor__header"><div><h1 id="editor-title">{text.title}</h1><p>{editor.project.slug}</p></div><span className={dirty ? "draft-indicator" : "saved-indicator"}>{dirty ? "Несохранённые изменения" : editor.draft ? "Черновик сохранён" : editor.project.status === "draft" ? "Новый черновик" : "Опубликован"}</span></div>
    <nav className="project-mode-navigation" aria-label="Разделы проекта"><button type="button" className={mode === "editor" ? "project-mode-navigation__item is-active" : "project-mode-navigation__item"} aria-current={mode === "editor" ? "page" : undefined} onClick={() => setMode("editor")}>Редактор</button><button type="button" className={mode === "history" ? "project-mode-navigation__item is-active" : "project-mode-navigation__item"} aria-current={mode === "history" ? "page" : undefined} onClick={() => setMode("history")}>История</button></nav>
    {error ? <div className="editor-error" role="alert" tabIndex={-1}><p>{error}</p>{error.includes("другой сессии") ? <button type="button" onClick={() => setConfirmReload(true)}>Загрузить актуальный черновик</button> : null}</div> : null}
    {mode === "editor" ? <div className="project-editor-flow">
      <ContentForm form={form} projectStatus={editor.project.status} autoSlug={editor.project.status === "draft"} update={update} updateLinks={updateLinks} linkErrors={linkErrors} linkValidationSummary={linkValidationSummary} />
      <EditorSection number="09" title="Галерея мобильной версии"><MediaSection galleryKind="mobile" locale={locale} items={groupItems("mobile")} uploading={uploading} onUpload={(file) => void addMedia(file, "mobile")} onMove={(position, direction) => reorder("mobile", position, direction)} onRemove={requestRemoval} onTextChange={(id, key, value) => update((next) => { const asset = next.media.find((item) => item.id === id); if (asset) asset.translations[locale][key] = value; })} onPresentationChange={(id, presentation) => update((next) => { const asset = next.media.find((item) => item.id === id); if (asset?.sourceType === "managed") asset.presentation = presentation; })} /></EditorSection>
      <EditorSection number="10" title="Галерея десктопной версии"><MediaSection galleryKind="desktop" locale={locale} items={groupItems("desktop")} uploading={uploading} onUpload={(file) => void addMedia(file, "desktop")} onMove={(position, direction) => reorder("desktop", position, direction)} onRemove={requestRemoval} onTextChange={(id, key, value) => update((next) => { const asset = next.media.find((item) => item.id === id); if (asset) asset.translations[locale][key] = value; })} onPresentationChange={(id, presentation) => update((next) => { const asset = next.media.find((item) => item.id === id); if (asset?.sourceType === "managed") asset.presentation = presentation; })} /></EditorSection>
      {uploading ? <p role="status">Загрузка и обработка изображения...</p> : null}
      <EditorSection number="11" title="Публикация"><div className="form-grid"><Field label="Порядок сортировки" type="number" value={String(form.sortOrder)} onChange={(value) => update((next) => { next.sortOrder = Number(value); })} /><label className="field"><span>Фактическая дата публикации</span><input value={editor.published?.publishedAt ?? ""} readOnly aria-readonly="true" /></label></div><p>Дата устанавливается системой при публикации.</p><p>Планирование станет доступно после реализации серверного расписания публикаций.</p><p>Опубликованная версия: {editor.published ? `v${editor.published.revisionNumber}` : "нет"}. Черновик: {editor.draft ? `v${editor.draft.revisionNumber}` : "нет"}.</p><div className="editor-actions project-editor-actions"><button type="button" onClick={() => void save()} disabled={saving || !dirty}>{saving ? "Сохранение..." : "Сохранить черновик"}</button><button type="button" ref={opener} onClick={requestPublish} disabled={publishing || dirty || !editor.draft}>{publishing ? "Публикация..." : "Опубликовать"}</button>{editor.published ? <button className="button-danger" type="button" onClick={() => setConfirmDeleteDraft(true)} disabled={deletingDraft || !editor.draft}>{deletingDraft ? "Удаление..." : "Удалить черновик"}</button> : <button className="button-danger" type="button" onClick={() => setConfirmDeleteProject(true)} disabled={deletingProject}>{deletingProject ? "Удаление..." : "Удалить проект"}</button>}<button type="button" disabled title="Планирование станет доступно после реализации серверного расписания публикаций.">Запланировать публикацию</button></div></EditorSection>
      <div key={reorderAnnouncement.sequence} aria-live="polite" aria-atomic="true" className="visually-hidden">{reorderAnnouncement.message}</div>
    </div> : <HistoryView history={history} loading={historyLoading} error={historyError} />}
    {confirming ? <AccessibleDialog title={`Опубликовать изменения «${form.translations[locale].title}»?`} description="Опубликованные данные проекта в публичном API будут заменены." confirmLabel="Опубликовать" busy={publishing} error={error} onCancel={() => setConfirming(false)} onConfirm={() => void publish()} /> : null}
    {confirmDeleteDraft ? <AccessibleDialog title="Удалить черновик?" description="Неопубликованные изменения будут потеряны. Проект, опубликованная версия и locale publications сохранятся." confirmLabel="Удалить черновик" busy={deletingDraft} error={error} onCancel={() => setConfirmDeleteDraft(false)} onConfirm={() => void removeDraft()} /> : null}
    {confirmDeleteProject ? <AccessibleDialog title="Удалить неопубликованный проект?" description="Будут безвозвратно удалены проект и все его черновики. Медиафайлы не удаляются из хранилища и остаются в штатной очистке. Опубликованные проекты удалить нельзя." confirmLabel="Удалить проект" busy={deletingProject} error={error} onCancel={() => setConfirmDeleteProject(false)} onConfirm={() => void removeProject()} /> : null}
    {confirmReload ? <AccessibleDialog title="Отменить локальные изменения и загрузить актуальный черновик?" description="Черновик из другой сессии заменит локальные несохранённые значения." confirmLabel="Отменить изменения и загрузить" cancelLabel="Остаться в редакторе" onCancel={() => setConfirmReload(false)} onConfirm={() => void reloadLatestDraft()} /> : null}
    {mismatch ? <AccessibleDialog title="Несовпадение ориентации" description={`${mismatch.width} × ${mismatch.height}. Всё равно добавить в выбранную галерею?`} confirmLabel="Добавить" cancelLabel="Отмена" busy={uploading} onCancel={() => setMismatch(null)} onConfirm={() => void addMedia(mismatch.file, mismatch.galleryKind, true)} /> : null}
    {removal ? <AccessibleDialog title={copy.removeTitle} description={copy.removeDescription} confirmLabel={copy.remove} cancelLabel={copy.cancel} busy={removing} error={error} onCancel={() => setRemoval(null)} onConfirm={confirmRemoval}>{removal.thumbnailUrl ? <img className="media-dialog-preview" src={removal.thumbnailUrl} alt="" /> : null}<p className="dialog-context">{removal.label} · {removal.position + 1}</p></AccessibleDialog> : null}
  </section>;
}

function HistoryView({ history, loading, error }: { history: ProjectRevision[]; loading: boolean; error: string | null }) {
  return <section className="project-history" aria-labelledby="project-history-title"><h2 id="project-history-title">История</h2><p>Ревизии отображаются только для просмотра; текущий черновик редактора не изменяется.</p>{loading ? <p role="status">Загрузка истории изменений...</p> : null}{error ? <p role="alert">{error}</p> : null}{!loading && !error && history.length === 0 ? <p>Ревизий пока нет.</p> : null}<ol className="project-history__list">{history.map((item) => <li key={item.revisionId}><p><strong>{item.revisionType === "published" ? "Опубликовано" : "Черновик"} v{item.revisionNumber}</strong> · {item.updatedAt}</p><pre>{JSON.stringify(item.content, null, 2)}</pre></li>)}</ol></section>;
}

function EditorSection({ number, title, children, description }: { number: string; title: string; children: ReactNode; description?: string }) {
  return <section className="project-editor-section" aria-labelledby={`project-editor-section-${number}`}><header className="project-editor-section__header"><span className="project-editor-section__number">{number}</span><div><h2 id={`project-editor-section-${number}`}>{title}</h2>{description ? <p>{description}</p> : null}</div></header>{children}</section>;
}

function ContentForm({ form, projectStatus, autoSlug, update, updateLinks, linkErrors, linkValidationSummary }: { form: DraftContent; projectStatus: string; autoSlug: boolean; update: (mutate: (next: DraftContent) => void) => void; updateLinks: (mutate: (next: DraftContent) => void) => void; linkErrors: LinkFieldErrors; linkValidationSummary: string | null }) {
  return <>
    <EditorSection number="01" title="Тип и статус" description="Отображаемые значения доступны на двух языках; служебные поля отделены и сохранены для backend-контракта."><div className="paired-fields"><Field label="Отображаемый тип — русский" value={form.translations.ru.displayType} onChange={(value) => update((next) => { next.translations.ru.displayType = value; })} /><Field label="Отображаемый тип — английский" value={form.translations.en.displayType} onChange={(value) => update((next) => { next.translations.en.displayType = value; })} /><Field label="Статус — русский" value={form.translations.ru.statusLabel} onChange={(value) => update((next) => { next.translations.ru.statusLabel = value; })} /><Field label="Статус — английский" value={form.translations.en.statusLabel} onChange={(value) => update((next) => { next.translations.en.statusLabel = value; })} /></div><div className="form-grid project-editor-section__technical"><Field label="Служебный тип проекта" value={form.projectType ?? ""} onChange={(value) => update((next) => { next.projectType = value || null; })} /><label className="field"><span>Технический статус записи</span><input value={projectStatus} readOnly aria-readonly="true" /></label><label className="field"><span>Ход проекта: {form.dates.ongoing ? "в процессе" : "завершён"}</span><input type="checkbox" checked={form.dates.ongoing} onChange={(event) => update((next) => { next.dates.ongoing = event.target.checked; if (event.target.checked) next.dates.endedAt = null; })} /></label></div></EditorSection>
    <EditorSection number="02" title="Название проекта"><div className="paired-fields"><Field label="Название — русский" value={form.translations.ru.title} onChange={(value) => update((next) => { next.translations.ru.title = value; if (autoSlug) { const slug = automaticSlug(value); if (slug) { next.slug = slug; next.galleryId = slug; } } })} /><Field label="Название — английский" value={form.translations.en.title} onChange={(value) => update((next) => { next.translations.en.title = value; if (autoSlug) { const slug = automaticSlug(value); if (slug) { next.slug = slug; next.galleryId = slug; } } })} /></div></EditorSection>
    <EditorSection number="03" title="Роль"><div className="paired-fields"><Field label="Роль — русский" value={form.translations.ru.role} onChange={(value) => update((next) => { next.translations.ru.role = value; })} /><Field label="Роль — английский" value={form.translations.en.role} onChange={(value) => update((next) => { next.translations.en.role = value; })} /></div></EditorSection>
    <EditorSection number="04" title="Описание"><div className="paired-fields"><label className="field"><span>Описание — русский</span><textarea value={form.translations.ru.description} rows={8} onChange={(event) => update((next) => { next.translations.ru.description = event.target.value; })} /></label><label className="field"><span>Описание — английский</span><textarea value={form.translations.en.description} rows={8} onChange={(event) => update((next) => { next.translations.en.description = event.target.value; })} /></label></div></EditorSection>
    <EditorSection number="05" title="Функции и задачи"><ContentBlocks form={form} update={update} collection="features" /></EditorSection>
    <EditorSection number="06" title="Технологии"><TechnologyCollection form={form} update={update} /></EditorSection>
    <EditorSection number="07" title="Примечания"><ContentBlocks form={form} update={update} collection="notes" /></EditorSection>
    <EditorSection number="08" title="Ссылки"><LinkCollection form={form} update={updateLinks} errors={linkErrors} summary={linkValidationSummary} /></EditorSection>
  </>;
}

function LinkCollection({ form, update, errors, summary }: { form: DraftContent; update: (mutate: (next: DraftContent) => void) => void; errors: LinkFieldErrors; summary: string | null }) {
  const normalize = (links: DraftContent["links"]) => links.forEach((link, position) => { link.sortOrder = (position + 1) * 10; });
  return <fieldset className="form-section"><legend>Ссылки проекта</legend>{summary ? <p role="alert">{summary}</p> : null}{form.links.map((link, index) => { const current = errors[link.id]; return <div className="paired-content-item" key={link.id}>{current?.row ? <p role="alert" id={`link-error-${link.id}-row`}>{current.row}</p> : null}<div className="paired-fields"><Field label="Название ссылки — русский" value={link.label.ru} error={current?.labelRu} errorId={`link-error-${link.id}-label-ru`} onChange={(value) => update((next) => { const item = next.links.find((candidate) => candidate.id === link.id); if (item) item.label.ru = value; })} /><Field label="Название ссылки — английский" value={link.label.en} error={current?.labelEn} errorId={`link-error-${link.id}-label-en`} onChange={(value) => update((next) => { const item = next.links.find((candidate) => candidate.id === link.id); if (item) item.label.en = value; })} /></div><Field label="Адрес ссылки" value={link.url} error={current?.url} errorId={`link-error-${link.id}-url`} onChange={(value) => update((next) => { const item = next.links.find((candidate) => candidate.id === link.id); if (item) item.url = value; })} /><div className="editor-actions"><button type="button" disabled={index === 0} aria-label={`Переместить ссылку ${index + 1} выше`} onClick={() => update((next) => { [next.links[index], next.links[index - 1]] = [next.links[index - 1]!, next.links[index]!]; normalize(next.links); })}>Переместить выше</button><button type="button" disabled={index === form.links.length - 1} aria-label={`Переместить ссылку ${index + 1} ниже`} onClick={() => update((next) => { [next.links[index], next.links[index + 1]] = [next.links[index + 1]!, next.links[index]!]; normalize(next.links); })}>Переместить ниже</button><button type="button" aria-label={`Удалить ссылку ${index + 1}`} onClick={() => update((next) => { next.links.splice(index, 1); normalize(next.links); })}>Удалить</button></div></div>; })}<button type="button" onClick={() => update((next) => { next.links.push({ id: crypto.randomUUID(), url: "", sortOrder: (next.links.length + 1) * 10, label: { ru: "", en: "" } }); })}>+ Добавить ссылку</button></fieldset>;
}

function ContentBlocks({ form, update, collection: name }: { form: DraftContent; update: (mutate: (next: DraftContent) => void) => void; collection: "features" | "notes" }) {
  const move = (items: Array<{ sortOrder: number }>, index: number, direction: -1 | 1) => { const target = index + direction; [items[index], items[target]] = [items[target]!, items[index]!]; items.forEach((item, position) => { item.sortOrder = (position + 1) * 10; }); };
  const itemTitle = name === "features" ? "Функция или задача" : "Примечание"; const addTitle = name === "features" ? "+ Добавить функцию или задачу" : "+ Добавить примечание";
  return <>{form[name].map((item, index) => <div className="paired-content-item" key={item.id}><div className="paired-fields"><Field label={`${itemTitle} — русский`} value={item.text.ru} onChange={(value) => update((next) => { next[name][index]!.text.ru = value; })} /><Field label={`${itemTitle} — английский`} value={item.text.en} onChange={(value) => update((next) => { next[name][index]!.text.en = value; })} /></div><div className="editor-actions"><button type="button" disabled={index === 0} aria-label={`Переместить ${itemTitle.toLowerCase()} выше`} onClick={() => update((next) => move(next[name], index, -1))}>Переместить выше</button><button type="button" disabled={index === form[name].length - 1} aria-label={`Переместить ${itemTitle.toLowerCase()} ниже`} onClick={() => update((next) => move(next[name], index, 1))}>Переместить ниже</button><button type="button" aria-label={`Удалить: ${itemTitle.toLowerCase()}`} onClick={() => update((next) => { next[name].splice(index, 1); next[name].forEach((value, position) => { value.sortOrder = (position + 1) * 10; }); })}>Удалить</button></div></div>)}<button type="button" onClick={() => update((next) => { next[name].push({ id: crypto.randomUUID(), sortOrder: (next[name].length + 1) * 10, text: { ru: "", en: "" } }); })}>{addTitle}</button></>;
}

function TechnologyCollection({ form, update }: { form: DraftContent; update: (mutate: (next: DraftContent) => void) => void }) {
  return <>{form.technologies.map((technology, index) => <div className="paired-content-item" key={index}><div className="paired-fields"><Field label="Название технологии" value={technology.name} onChange={(value) => update((next) => { next.technologies[index]!.name = value; })} /><Field label="Slug технологии" value={technology.slug} onChange={(value) => update((next) => { next.technologies[index]!.slug = value; })} /></div><div className="editor-actions"><button type="button" disabled={index === 0} onClick={() => update((next) => { [next.technologies[index], next.technologies[index - 1]] = [next.technologies[index - 1]!, next.technologies[index]!]; next.technologies.forEach((item, position) => { item.sortOrder = (position + 1) * 10; }); })}>Переместить выше</button><button type="button" disabled={index === form.technologies.length - 1} onClick={() => update((next) => { [next.technologies[index], next.technologies[index + 1]] = [next.technologies[index + 1]!, next.technologies[index]!]; next.technologies.forEach((item, position) => { item.sortOrder = (position + 1) * 10; }); })}>Переместить ниже</button></div></div>)}</>;
}

function MediaSection({ galleryKind, locale, items, uploading, onUpload, onMove, onRemove, onTextChange, onPresentationChange }: { galleryKind: ProjectGalleryKind; locale: Locale; items: DraftContent["media"]; uploading: boolean; onUpload: (file: File | undefined) => void; onMove: (position: number, direction: -1 | 1) => void; onRemove: (asset: DraftContent["media"][number], position: number) => void; onTextChange: (id: string, key: "alt" | "ariaLabel", value: string) => void; onPresentationChange: (id: string, presentation: MediaPresentation) => void }) {
  const copy = mediaCopy[locale]; const label = galleryKind === "mobile" ? copy.vertical : copy.horizontal; const description = galleryKind === "mobile" ? copy.verticalDescription : copy.horizontalDescription;
  return <div className="form-section" aria-labelledby={`${galleryKind}-media-title`}><h3 id={`${galleryKind}-media-title`} tabIndex={-1}>{label}</h3><p>{description}</p><label className="field"><span>{`Загрузить: ${label.toLowerCase()}`}</span><input aria-label={`Загрузить: ${label.toLowerCase()}`} type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={(event) => onUpload(event.target.files?.[0])} /></label>{items.length > 8 ? <p role="status">Рекомендуется не более 8 изображений в галерее.</p> : null}{items.map((asset, position) => <MediaItem key={asset.id} asset={asset} position={position} total={items.length} locale={locale} label={label} onMove={onMove} onRemove={onRemove} onTextChange={onTextChange} onPresentationChange={onPresentationChange} />)}</div>;
}

function MediaItem({ asset, position, total, locale, label, onMove, onRemove, onTextChange, onPresentationChange }: { asset: DraftContent["media"][number]; position: number; total: number; locale: Locale; label: string; onMove: (position: number, direction: -1 | 1) => void; onRemove: (asset: DraftContent["media"][number], position: number) => void; onTextChange: (id: string, key: "alt" | "ariaLabel", value: string) => void; onPresentationChange: (id: string, presentation: MediaPresentation) => void }) {
  const copy = mediaCopy[locale]; const managed = asset.sourceType === "managed" ? asset as ManagedMedia : null; const hasDimensions = Boolean(managed?.width && managed?.height);
  return <fieldset className="form-section"><legend>{label} · {managed ? "Загруженное изображение" : "Наследуемое изображение"}</legend>{asset.sourceType === "managed" ? <img className="media-preview" src={`${API_BASE_URL}/api/v1/media/${asset.assetId}/thumbnail`} alt="" /> : <p>{asset.src}</p>}<p className="media-metadata">{label} · {position + 1}</p><p className="media-dimensions">{managed && hasDimensions ? <><span aria-hidden="true">{managed.width} × {managed.height} px</span><span className="visually-hidden">{copy.imageDimensions(managed.width!, managed.height!)}</span></> : copy.dimensionsUnavailable}</p>{managed ? <label className="field"><span>Отображение изображения</span><select value={managed.presentation ?? "cover"} onChange={(event) => onPresentationChange(managed.id, event.target.value as MediaPresentation)}><option value="cover">Обрезать по контейнеру</option><option value="contain">Показать изображение целиком</option></select></label> : null}<div className="editor-actions"><button type="button" disabled={position === 0} aria-label={`Переместить изображение «${label}» вверх`} onClick={() => onMove(position, -1)}>Вверх</button><button type="button" disabled={position === total - 1} aria-label={`Переместить изображение «${label}» вниз`} onClick={() => onMove(position, 1)}>Вниз</button><button id={`media-remove-${asset.id}`} type="button" aria-label={`Удалить изображение «${label}» ${position + 1}`} onClick={() => onRemove(asset, position)}>Удалить</button></div><div className="form-grid"><Field label="Alt" value={asset.translations[locale].alt} onChange={(value) => onTextChange(asset.id, "alt", value)} /><Field label="Aria label" value={asset.translations[locale].ariaLabel} onChange={(value) => onTextChange(asset.id, "ariaLabel", value)} /></div></fieldset>;
}

function Field({ label, value, onChange, type = "text", disabled = false, error, errorId }: { label: string; value: string; onChange: (value: string) => void; type?: string; disabled?: boolean; error?: string; errorId?: string }) { return <><label className="field"><span>{label}</span><input type={type} value={value} disabled={disabled} aria-invalid={error ? true : undefined} aria-describedby={error ? errorId : undefined} onChange={(event) => onChange(event.target.value)} /></label>{error ? <span id={errorId} role="alert">{error}</span> : null}</>; }
